# Generated by Django 5.0.2 on 2024-02-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the FAQ Topic', max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('text', models.TextField(help_text='This is a help text', verbose_name='text field test')),
            ],
            options={
                'verbose_name': 'faq topic',
                'verbose_name_plural': 'faq topics',
            },
        ),
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duallang.homecarousel')),
            ],
        ),
    ]
